In [2]:
import numpy as np

data1 = []
with open("data1.txt","r") as f:
    for line in f:
        data1.append(float(line.strip()))
        
data1 = np.asarray(data1)

In [3]:
np.random.randint(50,size=(1,3))

array([[17, 47, 40]])

In [4]:

def expectation(data,num_class):
    class_weights = [1/num_class]*3
    sd =np.random.randint(10,50,size=(1,num_class))
    mean = np.random.randint(1,10,size=(1,num_class))
    prob = []
    for i in data:
        bottom = 0
        class_prob =[]
        for j in range(num_class):
            part1 = np.log(1/(np.sqrt(2*np.pi*sd[0][j])))
            part2 = (-((i-mean[0][j])**2/2*(sd[0][j]**2)))
            upper = (part1 + part2)*class_weights[j]
            class_prob.append(upper)
            bottom += upper
        prob.append(class_prob/bottom)
    prob=np.asmatrix(prob)
    count= prob.sum(axis=0)
    return prob,count

In [5]:
prob,count = expectation(data1,3)

In [6]:
def maximization(prob,count,data):
    data = np.asmatrix(data)
    weighted_points = np.multiply(prob,(np.transpose(data)*np.matrix([1,1,1])))
    new_means = weighted_points.sum(axis=0)/count[0]
    data_2 = np.multiply(data,data)
    weighted_points_2 = np.multiply(weighted_points,weighted_points)
    part1 = np.multiply(prob,(np.transpose(data_2)*np.matrix([1,1,1]))).sum(axis=0)/count[0]
    part2 = weighted_points_2.sum(axis=0)/count[0]
    new_sd = np.sqrt(part1-part2)

    return

In [201]:
count[0]/count.sum()

matrix([[ 0.00607208,  0.23576996,  0.75815795]])

In [190]:
prob

matrix([[ 0.03820007,  0.95468642,  0.00711351],
        [ 0.03480406,  0.96191577,  0.00328016],
        [ 0.0384582 ,  0.95408171,  0.00746009],
        ..., 
        [ 0.0431734 ,  0.94174677,  0.01507982],
        [ 0.03219853,  0.9664952 ,  0.00130627],
        [ 0.0318265 ,  0.96707631,  0.00109719]])

In [191]:
count[0]

matrix([[  17.85038776,  479.70868847,    2.44092376]])

In [133]:
t = np.transpose(np.asmatrix(data1))*np.matrix([1,1,1])

In [7]:
np.exp(-72.79/2304)

0.96890095886919525

In [8]:
from matplotlib import pyplot as plt